#!/bin/sh

cabal build
cp --remove-destination "./dist-newstyle/build/x86_64-linux/ghc-9.4.6/xmonad-config-0.1.0.0/x/xmonad-x86_64-linux/build/xmonad-x86_64-linux/xmonad-x86_64-linux" "$1"
cp --remove-destination "./dist-newstyle/build/x86_64-linux/ghc-9.4.6/xmonad-config-0.1.0.0/x/taffybar/build/taffybar/taffybar" "$(dirname "$1")/taffybar"

